### ISSUE TITLE
Erro Vip system Aio System

### ISSUE THREAD

**Issue by Hu3Brasil** [L2jBrasil/L2jBrasil#1]
Da esse erro ao tentar dar vip ou aio a um Player.

https://imgur.com/a/dEkzg

Tipo acaba de logar um char e tenta dar vip e aio a ele acontece esse erro.

**Comment by L2JBrasilTutorial** [comment]
Obrigado por contribuir com nosso projeto, estarei atualizando os códigos de AIO e VIP por que foi desse projeto que saiu o primeiro código desse MOD, quando na época nosso ex membro da Equipe Khayruss fez o mod, mas nosso projeto ficou parado e só as outras revisões atualizaram os códigos desse MOD.

**Comment by Tayran** [comment]
Obrigado por contribuir com nosso projeto, estarei atualizando os códigos de AIO e VIP por que foi desse projeto que saiu o primeiro código desse MOD, quando na época nosso ex membro da Equipe Khayruss fez o mod, mas nosso projeto ficou parado e só as outras revisões atualizaram os códigos desse MOD.

**Comment by Tayran** [comment]
Fiz testes aqui e na verdade o erro não tem a ver com o MOD, tem a ver com o erro reportado no issue #2, arrumando o erro do primeiro arruma esse aqui também, pode testar que se o char morrer uma vez como reportado no outro Issue, você conseguirá dar AIO para o player. Obrigado.
