### ISSUE TITLE
Optimizar o HikariCP

### ISSUE THREAD

**Issue by queued** [L2jBrasil/L2jBrasil#17]
### Descrição
A mudança pra HikariCP feita no projeto, apesar de inicial, ainda pode ser melhorada com algumas configurações extras. A troca de subclasse na l2jbr3 está demorando 3 segundos pra ser feita, mesmo com o HikariCP ativado.

### Proposta de ajuste
Veja [neste arquivo](https://github.com/la2eden/la2eden/blob/master/java/com/la2eden/commons/database/DatabaseFactory.java#L45) da linha 45/46, até a linha 69 as configurações boas para um servidor L2J. Fiz alguns testes na minha revisão, e SEM essas configurações e SEM o FloodProtector, a troca de subclasse demora 1,8 segundos. agora COM essas configurações e SEM o FloodProtector, a troca foi imediata. O motivo é o Cache estar ativo para queries que passam pelo DataSource. Na source da l2jbr3, a troca foi instantânea também (no segundo cenário).

**Comment by LeonanCarvalho** [comment]
Olá @queued bacana, se você quiser, pode fazer as alterações e mandar um pull request pra gente, vamos analizar as alterções e jogá-la para o nosso branch de desenvolvimento.

**Comment by queued** [comment]
#20 prontinho.
