### ISSUE TITLE
Comand Fail

### ISSUE THREAD

**Issue by AdenilsonMartins** [L2jBrasil/L2jBrasil#19]
Salve, o comando **//recall NickdoPlayer** não esta pegando, se for restrição, sorry!
E o **//admin - Game - List.** tbm  não aparece o player, se for restrição, perdoem minha falta de sabedoria. 
[http://prntscr.com/h7r95z](url)

**Comment by queued** [comment]
Você pode mandar uma foto do chat quando usa o comando *//recall <player>*?

**Comment by queued** [comment]
Deixa pra lá. Já achei o erro e já corrigi. Vou fazer o pull-request agora mesmo.

**Comment by queued** [comment]
Veja o commit #22. Ele resolve o problema do comando //recall. O outro comando eu ainda estou verificando.

**Comment by LeonanCarvalho** [comment]
closes #19
