### ISSUE TITLE
Add dependencies management 

### ISSUE THREAD

**Issue by JoeAlisson** [L2jBrasil/L2jBrasil#31]
Putting the binary dependencies inside the project is not a good practice. In this way the bug fixes on theses libraries can be missed. 

Using [Gradle](https://gradle.org/) or [Maven](https://maven.apache.org/) would be nice.

**Comment by LeonanCarvalho** [comment]
I agree.

I think we can use Grandle, just because the configuration files are more verbose. 


PS: Whats your nickname at l2jbrasil.com @JoeAlisson?

**Comment by JoeAlisson** [comment]
Haha, KhayrusS
