### ISSUE TITLE
Review droplist of the Quest "Path to a Warrior"

### ISSUE THREAD

**Issue by LeonanCarvalho** [L2jBrasil/L2jBrasil#33]
### Descrição/Description
The quest item  `Rusted Bronze Sword` is only dropping from Tracker Skeleton (20035) but also can be droped from `Tracker Skeleton Leader` (20042) as said in the quest (And I did this quest thousand times )

![image](https://user-images.githubusercontent.com/3593706/32864043-ca913f76-ca44-11e7-8dbe-a247a417b94f.png)

Maybe a full review of quests is needed.

**Comment by Tayran** [comment]
3. Trader Simplon gives you the task of collecting 10 Rusted Bronze Swords. To do this you must travel to the northwest walled area of the Ruins of Agony, which is west of Gludio, and kill level 17 Tracker Skeletons and level 18 Tracker Skeleton Leaders.

This is ok.

**Comment by LeonanCarvalho** [comment]
Não Tayran, tem que dropar dos 2... Fiz essa quest dezenas de vezes no oficial.

**Comment by LeonanCarvalho** [comment]
Realmente no arquivo de quest [está constando o drop](
https://github.com/L2jBrasil/L2jBrasil/blob/master/L2JBrasil_DP/data/jscript/quests/401_PathToWarrior/__init__.py#L124)... mas não dropou matei uns 10 e não veio o item, só quando eu comecei a matar o Tracker Skeleton que veio, e 100% de chance.

**Comment by Tayran** [comment]
Leonan eu fiz todos os testes e a quest completa, os itens caíram dos dois, fiz minha quest quase toda matando o Leader, vou fechar o issue por que está tudo ok.
