### ISSUE TITLE
data/html/default/blessingofprotection.htm is missing

### ISSUE THREAD

**Issue by LeonanCarvalho** [L2jBrasil/L2jBrasil#34]
### Descrição/Description
Text missing from Newbie Guide

### Proposta de ajuste (opcional) / Fix Proposal (optional)
Review all htm from l2jserver  and update ours.

### Anexos/ Attachments (printscreen, links ,etc )
![image](https://user-images.githubusercontent.com/3593706/32864143-0ca92cd4-ca45-11e7-956f-4de2bcfb21b9.png)

**Comment by LeonardoHolanda** [comment]
Há dois arquivos .htm idênticos com esse nome. Na sua print está dando erro pois os arquivos não estão em Lowcaser e já na script está.

**Comment by Tayran** [comment]
Fixed.

**Comment by LeonanCarvalho** [comment]
Provavelmente problema por conta do linux, já que é case sensitive não encontrou o arquivo. Precisamos ter cautela com isso.
Vamos adotar um padrão CamelCase ou lowercase mesmo para essas coisas.

**Comment by Tayran** [comment]
Não, Isso se comporta da mesma forma no Windows, era só um erro mesmo.
