### ISSUE TITLE
/targetnext não está funcionando

### ISSUE THREAD

**Issue by LeonanCarvalho** [L2jBrasil/L2jBrasil#36]
### Descrição
A ação /targetnext não está funcionando, nem pelo botão nem pelo comando.

**Comment by Tayran** [comment]
Está funcionando sim, abra o arquivo commandname-e da sua system e olhe se essas linhas estão assim, eu testei no server que está online : 

**13	12	a,target\0
14	13	a,targetnext\0
**

**Comment by LeonanCarvalho** [comment]
Me envia seu arquivo então, eu fiz instalação limpa ontem, subi so as dlls para poder funcionar no win10..

**Comment by Tayran** [comment]
Aqui está.
[commandname-e.zip](https://github.com/L2jBrasil/L2jBrasil/files/1477000/commandname-e.zip)
