### ISSUE TITLE
Commemorative Item: First Anniversary of Lineage II Service

### ISSUE THREAD

**Issue by LeonanCarvalho** [L2jBrasil/L2jBrasil#37]
[PT-BR]
Esse item deveria summonar o wyvern?

[EN]
Should this item summon the wyvern?

**Comment by Tayran** [comment]
Não, isso é um item que no oficial foi de evento, o item que sumona um wynvern é 8663

**Comment by LeonanCarvalho** [comment]
8663 é o Enlightenment Oil, não é o item que deixa a cabeça grande? 
Eu tive um l2off a milénios atrás e esse item que era usado para summonar o wyvern... não tenho referências à esse item no oficial... até pq né..  mas ok então :)

**Comment by Tayran** [comment]
Não, no L2OFF isso seria tipo um item customizado para fazer isso, e não o potion de Big Head se chama Mastery Potion.
