### ISSUE TITLE
Mage acertando poucos danos!

### ISSUE THREAD

**Issue by NattanFelipe** [L2jBrasil/L2jBrasil#41]
Notei que mage tá acertando poucos danos, tipo 3 de dano de mob do mesmo level.
![image](https://user-images.githubusercontent.com/33167683/32975563-ac5d132a-cbef-11e7-8503-ae206e8953d1.png)

As vezes o ataque falha, mas batendo com a espada normal ele mata o mob.

**Comment by NattanFelipe** [comment]
![image](https://user-images.githubusercontent.com/33167683/32975592-de76c93c-cbef-11e7-8c93-f049c6cc53e1.png)
No mob da mesma área! =)

**Comment by LeonanCarvalho** [comment]
Esses golens  tem resistência à magina, talvez a skill de resistência mágica esteja protegendo muito.

**Comment by NattanFelipe** [comment]
Problema que não foi apenas os golens brother, vi que as aranhas tbm tem uma baita defesa se for o caso. Acho que a resistência deles tá com algum problema!

**Comment by LeonanCarvalho** [comment]
Você está com todas as mensagens ativas? Tem questão da mensagem falhar..
Se eu eu não me engano esse lugar é para grade D e skills de segunda job... experimenta usando esses itens pra ver ..

**Comment by LeonanCarvalho** [comment]
Outra dica, 
Para testar essa área vc deveria estar no lvl 32~35 já com as skills de primeira job e um item D básico.
E buffs básico de acumem e alvez um empower lvl1.
Se mesmo assim o dano estiver baixo realmente temos um problema.

**Comment by NattanFelipe** [comment]
Pois é, fiz com um personagem normal, vou testar novamente ai com itens grade d e tudo certinho, mas também vou dar uma analisada na skill de resistência contra mage!
Eu acho que temos um probleminha ai, mas vou averiguar certinho para falar.
