### ISSUE TITLE
GK Nobles não funciona!

### ISSUE THREAD

**Issue by NattanFelipe** [L2jBrasil/L2jBrasil#48]
Galera, há um tempo atrás eu refiz todos os GK do projeto L2JDREAM, com teleports nobles, adena corretinha, tinha também um evento de um certo dia que reduzia o valor das GK em um período do dia. 
**Notei que no nosso projeto não está funcionando a GK nobles. Elas também não tem o evento que reduz o preço da GK em um determinado horário do dia!** 
![image](https://user-images.githubusercontent.com/33167683/33455430-2b6aa7b4-d603-11e7-947a-e2debd1cffe7.png)
Eu queria refazer essas GK, colocando todos os teleports, locs, preços e etc. 

Os que eu fiz para o l2jdream foram todos testados 100% e sem nenhum erro, ficou um diferencial grande e visível para o projeto.

**Comment by Tayran** [comment]
Nattan isso da GK ai ta acontecendo com qualquer GK de qualquer cidade ? Quanto as correções que quer fazer e modificações, se não for fugir o padrão do jogo pode fazer, e estarei olhando isso assim que tiver tempo livre.

**Comment by NattanFelipe** [comment]
@Tayran não irá fugir dos padrões do jogo, sem duvidas. É os teleports normais!

**Comment by LeonardoHolanda** [comment]
[Fixado.](https://github.com/L2jBrasil/L2jBrasil/commit/47a1f34814c26f588e6c5f4d7a3ba57a962baeab)
