### ISSUE TITLE
Skill ID 1411 - Mystic Immunity

### ISSUE THREAD

**Issue by slym-seifer** [L2jBrasil/L2jBrasil#49]
Boa noite, Skill Mystic Immunity ID - 1411- Não esta funcionando corretamente, segue anexado.
![shot00000](https://user-images.githubusercontent.com/34143392/33457498-d0187826-d609-11e7-9ae6-6461c4db7f7c.jpg)

**Comment by slym-seifer** [comment]
ela deixa o alvo imune aos debuffs e buffs, porem só esta funcionando contra os debuffs. 
![capturar](https://user-images.githubusercontent.com/34143392/33458342-05595a98-d60d-11e7-8c18-a91a4226a1f6.PNG)

**Comment by Tayran** [comment]
Obrigado, acho que maior parte dos projetos não tem isso corrigido, vou mandar a correção agora.

Muito obrigado pela disposição em ajudar e riqueza em informações, que é crucial.
