### ISSUE TITLE
2 Configs iguais

### ISSUE THREAD

**Issue by Hu3Brasil** [L2jBrasil/L2jBrasil#5]
l2jbrasil.properties

Allow players to run multiple windows with a single **IP** address.
AllowDualBox = False
AllowedBoxes = 1
**AllowDualBoxInOly = False           <-----------**
AllowDualBoxInEvent = False

 True = Allow same **IP** olympiad matches
 False = Don't allow same **IP** Olympiad matches.
 Default : True
 **AltOlySameIP = True                     <-----------**

**Comment by Tayran** [comment]
Obrigado, realmente está com dois códigos para a mesma coisa, apesar de a config de baixo está escrita de forma errada, mas ela funciona no core, só o 'P' é minúsculo, na próxima release já estará consertado.
