### ISSUE TITLE
Command Channel - Visual Bug

### ISSUE THREAD

**Issue by slym-seifer** [L2jBrasil/L2jBrasil#50]
Esse é um "duplo-bug", entretanto, apenas visual, não possui grande relevância no desenrolar do jogo.

**1 - Para se criar um Command Channel é necessario que o player tenha em seu inventario (Ao menos um) "Strategy Map" (Adquirido na Grocery).**
Ao se criar o CC, não esta sendo requerido o item.

2 - Conforme mostrado na figura a seguir, quando o CC é criado a janela "Allied Force Information" não acompanha os dados reais do CC (Na figura, representado no Chat System do lado inferior esquerdo).
E quando encerrada as partys, a janela não se fecha. 

![cc bug](https://user-images.githubusercontent.com/34143392/33460954-9308c180-d617-11e7-921a-1df11a43a722.PNG)

**Comment by Tayran** [comment]
Os bugs citados foram corrigidos, e olhei aqui no código a parte de pedir um Strategy Guide está correta presente na source : 
```
		else if (requestor.getInventory().getItemByItemId(8871) != null) // 8871 Strategy Guide. Should destroyed after sucessfull invite?
			hasRight = true;

```
