### ISSUE TITLE
Slot Buff/Debuffs Bug

### ISSUE THREAD

**Issue by slym-seifer** [L2jBrasil/L2jBrasil#51]
Segue alguns bugs relacionados aos slots de buffs e debuffs:
 - Na figura a seguir você verá um bug referente a quantidade de slot para buffs ao qual no "Default" pede para usar 24, abaixei para 20 e mesmo assim ingame é notado que a quantidade de slots fica 25.
![slots buffs bug](https://user-images.githubusercontent.com/34143392/33462442-bab7c8fa-d61e-11e7-996a-9124bcfc64b3.PNG)

 - Os buffs, debuffs e potions não são separados como no retail like, gerando uma certa "confusão" na hora da contagem por parte do servidor, como por exemplo, quando se possui um debuff ou potion "entre" os slots de buffs, o debuff ou potion é calculado como um buff e portanto eu ficarei com menos um slot, exemplo pratico em foto anexada:
![slots debuff bug](https://user-images.githubusercontent.com/34143392/33462759-9b9cc342-d620-11e7-97d8-efa63986d59b.PNG)

como podem ver, os debuffs e potions ocupam os slots dos buffs, no retail existe uma separação.

**Comment by Tayran** [comment]
Fiz testes aqui e referente aos slots de buff está tudo ok, perceba que quando puxamos todas as skills do personagem pelo admin vem junto as Divine inspiration e faz com que tenha 4 buffs a mais do que a contagem normal, coloquei 15 buffs e removi meu divine inspiration e pegou só 15 buffs, e depois adicionei divine level 4 e pegou 19 buffs, o Bug das doenças de hot springs não sendo tratado como Debuff foi arrumado era só elas que estavam assim, Quanto aos slots de buff estamos olhando isso em uma plataforma retail só para certeza de qual forma é a certa e ai faremos a correção, obrigado pelo apoio.
