### ISSUE TITLE
Servidor não tem algumas scripts

### ISSUE THREAD

**Issue by NattanFelipe** [L2jBrasil/L2jBrasil#54]
Galera, andei olhando umas coisas e notei que o servidor não tem a script de teleport para o Antharas Lair, Valakas Lair e o teleport noblesse!

**Comment by LeonardoHolanda** [comment]
[Fixado.](https://github.com/L2jBrasil/L2jBrasil/commit/47a1f34814c26f588e6c5f4d7a3ba57a962baeab)
