### ISSUE TITLE
Bugg Skill Mirage Dagger

### ISSUE THREAD

**Issue by saimongbi** [L2jBrasil/L2jBrasil#6]
![image](https://user-images.githubusercontent.com/33363527/32401245-6ae2fb88-c0f2-11e7-9c9f-f09de3ce739f.png)
toda vez que uso skill mirage da erro no game server, Fake death tbm ! :)
a skill MIRAGE não ativa, e da erro no game server !

**Comment by Tayran** [comment]
Fixado. Obrigado por reportar.
