### ISSUE TITLE
skills Accuracy,Vicious Stance, Focus Skill Mastery

### ISSUE THREAD

**Issue by saimongbi** [L2jBrasil/L2jBrasil#7]
Essas skills para serem ativadas quando clica, porem elas ativa mais o incone da mesma não aparece em cima como buffer. 
mostra que foi ativada, porem elas não aparecem acima !

**Comment by LeonanCarvalho** [comment]
Não tenho certeza se no interlude elas aparecem no buff stack junto com os buffs, vamos investigar.

**Comment by Tayran** [comment]
Fiz o teste na source e isso não está acontecendo.
![captura de tela 46](https://user-images.githubusercontent.com/13998136/32522539-de6078f6-c3fe-11e7-8dd7-8ba25c29614d.png)
