### ISSUE TITLE
Erro l2World

### ISSUE THREAD

**Issue by Hu3Brasil** [L2jBrasil/L2jBrasil#8]
O bug continua vo usar como exemplo a list qnd logo um char adm(pra poder ver a list) ele aparece la Ok.
ai eu logo outro char desaparece o adm da list e fica so esse char se eu (  relogar o adm aparece so ele). isso ta gerando varios bug

**Comment by LeonanCarvalho** [comment]
@Hu3Brasil  Poderia fornecer mais informações? O arquivo de log de erro seria interessante ou pelo menos uma print screen com a maior parte do erro visível.

**Comment by Hu3Brasil** [comment]
Ficam varios Chars Online mas e como se eles nao estivesem, se tentar dar aio,vip.. pros chars que n aparecem na list da erro no Gs e eles n recebem O tayran ja tentou arrumar mas n deu muito certo

**Comment by Tayran** [comment]
Eu ainda não tive tempo desde aquele commit, mas eu havia testado antes e depois e aqui tinha tudo resolvido, farei novos testes hoje e estarei olhando isso e outras coisas.
