### ISSUE TITLE
MySQL TO MongoDB

### ISSUE THREAD

**Issue by WeenderT** [L2jBrasil/L2jBrasil#9]
Não a possibilidade de alterar o mysql para um banco noSQL ( MongoDB)

Ou até mesmo o java para node.js ?

**Comment by LeonanCarvalho** [comment]
É nossa inteição migrar alguns mecanismos para NoSQL, muito provavelmente MongoDB.

Porém migrar de java para node.js precisaria de uma inteira refatoração do código e acredito não haver ganho de performance que justifique tal migração.
